FROM hub.test.com/micro-service/java:8-jre
MAINTAINER developerName xxx@163.com

COPY target/course-edge-service-1.0-SNAPSHOT.jar /course-edge-service.jar

ENTRYPOINT ["java", "-jar", "/course-edge-service.jar"]
