FROM hub.test.com/micro-service/java:8-jre
MAINTAINER developerName xxx@163.com

COPY target/user-dubbo-service-1.0-SNAPSHOT.jar /user-dubbo-service.jar

ENTRYPOINT ["java", "-jar", "/user-dubbo-service.jar"]
