FROM hub.test.com/micro-service/java:8-jre
MAINTAINER developerName xxx@163.com

COPY target/course-dubbo-service-1.0-SNAPSHOT.jar /course-dubbo-service.jar

ENTRYPOINT ["java", "-jar", "/course-dubbo-service.jar"]
